### ISSUE TITLE
CUDA out of memory RuntimeError with NLG with batch_size=2

### ISSUE THREAD

**Issue by Migabaj** [adapter-hub/adapter-transformers#585]
## Environment info

     
- `adapter-transformers` version: 3.2.1
- Platform: Linux-4.15.0-142-generic-x86_64-with-glibc2.10
- Python version: 3.8.5
- Huggingface_hub version: 0.15.1
- PyTorch version (GPU?): 1.11.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

## Information

**Model I am using:** [`stefan-it/secret-gpt2`](https://huggingface.co/stefan-it/secret-gpt2) as an instance of `GPT2AdapterModel`.

**Language I am using the model on:** German.

**Adapter setup I am using (if any):** Trying to use the basic bottleneck adapter.

The problem arises when I try to train an adapter with a batch size any larger than 1. It outputs this error:

```
RuntimeError: CUDA out of memory. Tried to allocate 3.07 GiB (GPU 0; 31.75 GiB total capacity; 3.93 GiB already allocated; 528.19 MiB free; 4.03 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF]
```

## To reproduce

Here's all the code I used. You can set the paths however you want.

```
import os
from datasets import Dataset
from transformers import AutoTokenizer, GPT2AdapterModel, \
  DataCollatorForLanguageModeling, TrainingArguments, AdapterTrainer

DATA_DIR = # path
DATA_FILENAME = # path
DATA_PATH = os.path.join(DATA_DIR, DATA_FILENAME)

ADAPTER_DIR = # path
ADAPTER_NAME = # path
ADAPTER_PATH = os.path.join(ADAPTER_DIR, ADAPTER_NAME)

DEVICE = "cuda"
CACHE_DIR = # path
TRAIN_TEST_SPLIT = 0.2

def encode_batch(batch):
  return tokenizer(batch["text"],
                   truncation=True,
                   max_length=1024,
                   padding="max_length")

model = GPT2AdapterModel.from_pretrained("stefan-it/secret-gpt2", cache_dir=CACHE_DIR).to(DEVICE)
tokenizer = AutoTokenizer.from_pretrained("stefan-it/secret-gpt2", cache_dir=CACHE_DIR)
tokenizer.pad_token = tokenizer.eos_token
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

model.add_adapter("bottleneck")
model.add_causal_lm_head("bottleneck")
model.train_adapter("bottleneck")

with open(DATA_PATH, 'r', encoding='utf-8') as f:
  lines = f.readlines()

data_dict = {"text": lines}
dataset = Dataset.from_dict(data_dict)
dataset = dataset.train_test_split(TRAIN_TEST_SPLIT, shuffle=True)

dataset = dataset.map(encode_batch, batched=True)
dataset.set_format(type="torch", columns=["input_ids", "attention_mask"])

training_args = TrainingArguments(
    learning_rate=1e-4,
    num_train_epochs=6,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    logging_steps=200,
    output_dir="./training_output",
    overwrite_output_dir=True,
    remove_unused_columns=False,
)

adapter_trainer = AdapterTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    data_collator=data_collator,
)

if __name__ == "__main__":
    adapter_trainer.train()
    model.save_adapter(ADAPTER_PATH, "bottleneck")
```

The file used for the dataset contains 100 lines of German text.

## Expected behavior

I honestly expected it to be able to deal with larger quantities of data. Because of this, I'm not sure whether there is no mistake on my end. The server has had GPT2 models fine-tuned on it, so I am confused as to why an adapter breaks it so easily.

Is it a known issue and is there any way to mitigate this?

**Comment by hSterz** [comment]
Hello @Migabaj , CUDA memory errors can be caused by a number of factors. I tried the code in a google colab session with a GPU. I didn't face any problems during this. Here are some things to keep in mind for adapter training:
- The model weights (in this case `stefan-it/secret-gpt2`) are not updated during training. However, for the backwards pass, they still need to be on the GPU.
- The batch size heavily influences the Memory requirements (although 2 is a rather small batch size)
- The error message sounds like only a small portion of the GPU memory can be allocated for the model training maybe other programs are also using the GPU memory in the background.

I hope this helps.

**Comment by julianpollmann** [comment]
Hey @Migabaj, I had this error in a multi-GPU setup using AdapterTrainer. This works using a single GPU or with the standard HF Trainer, so the AdapterTrainer might have a problem with multiple GPUs.
You could try this:
`CUDA_VISIBLE_DEVICES={YOUR_DEVICE_NO} python training_script.py`

**Comment by Migabaj** [comment]
> Hey @Migabaj, I had this error in a multi-GPU setup using AdapterTrainer. This works using a single GPU or with the standard HF Trainer, so the AdapterTrainer might have a problem with multiple GPUs. You could try this: `CUDA_VISIBLE_DEVICES={YOUR_DEVICE_NO} python training_script.py`

Worked like a charm! Thank you so much!
